version: '3'

services:
    api:
        image: hermosa/api
        build: ./
        ports:
          - 80:9000
        environment:
          - API_DATABASE_URL=db:3306/api
    db:
        image: mysql
        ports:
          - 3306:3306
        environment:
          - MYSQL_ALLOW_EMPTY_PASSWORD=yes
          - MYSQL_DATABASE=api
          - MYSQL_ROOT_PASSWORD=api
