// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/iga.proto

/*
Package api is a generated protocol buffer package.

It is generated from these files:
	api/iga.proto

It has these top-level messages:
	GetGeneRequest
	GetGeneResponse
	GetEvaluationRequest
	GetEvaluationResponse
	SetEvaluationRequest
	SetEvaluationResponse
	Evaluation
	Gene
*/
package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetGeneRequest struct {
}

func (m *GetGeneRequest) Reset()                    { *m = GetGeneRequest{} }
func (m *GetGeneRequest) String() string            { return proto.CompactTextString(m) }
func (*GetGeneRequest) ProtoMessage()               {}
func (*GetGeneRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type GetGeneResponse struct {
	Genes []*Gene `protobuf:"bytes,1,rep,name=genes" json:"genes,omitempty"`
}

func (m *GetGeneResponse) Reset()                    { *m = GetGeneResponse{} }
func (m *GetGeneResponse) String() string            { return proto.CompactTextString(m) }
func (*GetGeneResponse) ProtoMessage()               {}
func (*GetGeneResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GetGeneResponse) GetGenes() []*Gene {
	if m != nil {
		return m.Genes
	}
	return nil
}

type GetEvaluationRequest struct {
}

func (m *GetEvaluationRequest) Reset()                    { *m = GetEvaluationRequest{} }
func (m *GetEvaluationRequest) String() string            { return proto.CompactTextString(m) }
func (*GetEvaluationRequest) ProtoMessage()               {}
func (*GetEvaluationRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type GetEvaluationResponse struct {
	Evaluations []*Evaluation `protobuf:"bytes,1,rep,name=evaluations" json:"evaluations,omitempty"`
}

func (m *GetEvaluationResponse) Reset()                    { *m = GetEvaluationResponse{} }
func (m *GetEvaluationResponse) String() string            { return proto.CompactTextString(m) }
func (*GetEvaluationResponse) ProtoMessage()               {}
func (*GetEvaluationResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GetEvaluationResponse) GetEvaluations() []*Evaluation {
	if m != nil {
		return m.Evaluations
	}
	return nil
}

type SetEvaluationRequest struct {
	Evaluations []*Evaluation `protobuf:"bytes,1,rep,name=evaluations" json:"evaluations,omitempty"`
}

func (m *SetEvaluationRequest) Reset()                    { *m = SetEvaluationRequest{} }
func (m *SetEvaluationRequest) String() string            { return proto.CompactTextString(m) }
func (*SetEvaluationRequest) ProtoMessage()               {}
func (*SetEvaluationRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *SetEvaluationRequest) GetEvaluations() []*Evaluation {
	if m != nil {
		return m.Evaluations
	}
	return nil
}

type SetEvaluationResponse struct {
}

func (m *SetEvaluationResponse) Reset()                    { *m = SetEvaluationResponse{} }
func (m *SetEvaluationResponse) String() string            { return proto.CompactTextString(m) }
func (*SetEvaluationResponse) ProtoMessage()               {}
func (*SetEvaluationResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type Evaluation struct {
	Geneid int32 `protobuf:"varint,1,opt,name=geneid" json:"geneid,omitempty"`
	Value  int32 `protobuf:"varint,2,opt,name=value" json:"value,omitempty"`
}

func (m *Evaluation) Reset()                    { *m = Evaluation{} }
func (m *Evaluation) String() string            { return proto.CompactTextString(m) }
func (*Evaluation) ProtoMessage()               {}
func (*Evaluation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Evaluation) GetGeneid() int32 {
	if m != nil {
		return m.Geneid
	}
	return 0
}

func (m *Evaluation) GetValue() int32 {
	if m != nil {
		return m.Value
	}
	return 0
}

type Gene struct {
	Id          int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	WheelRadius int32 `protobuf:"varint,2,opt,name=wheel_radius,json=wheelRadius" json:"wheel_radius,omitempty"`
	Begin       int32 `protobuf:"varint,3,opt,name=begin" json:"begin,omitempty"`
	PointNum    int32 `protobuf:"varint,4,opt,name=point_num,json=pointNum" json:"point_num,omitempty"`
	BreastWide  int32 `protobuf:"varint,5,opt,name=breast_wide,json=breastWide" json:"breast_wide,omitempty"`
}

func (m *Gene) Reset()                    { *m = Gene{} }
func (m *Gene) String() string            { return proto.CompactTextString(m) }
func (*Gene) ProtoMessage()               {}
func (*Gene) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *Gene) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Gene) GetWheelRadius() int32 {
	if m != nil {
		return m.WheelRadius
	}
	return 0
}

func (m *Gene) GetBegin() int32 {
	if m != nil {
		return m.Begin
	}
	return 0
}

func (m *Gene) GetPointNum() int32 {
	if m != nil {
		return m.PointNum
	}
	return 0
}

func (m *Gene) GetBreastWide() int32 {
	if m != nil {
		return m.BreastWide
	}
	return 0
}

func init() {
	proto.RegisterType((*GetGeneRequest)(nil), "api.GetGeneRequest")
	proto.RegisterType((*GetGeneResponse)(nil), "api.GetGeneResponse")
	proto.RegisterType((*GetEvaluationRequest)(nil), "api.GetEvaluationRequest")
	proto.RegisterType((*GetEvaluationResponse)(nil), "api.GetEvaluationResponse")
	proto.RegisterType((*SetEvaluationRequest)(nil), "api.SetEvaluationRequest")
	proto.RegisterType((*SetEvaluationResponse)(nil), "api.SetEvaluationResponse")
	proto.RegisterType((*Evaluation)(nil), "api.Evaluation")
	proto.RegisterType((*Gene)(nil), "api.Gene")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Genes service

type GenesClient interface {
	Get(ctx context.Context, in *GetGeneRequest, opts ...grpc.CallOption) (*GetGeneResponse, error)
}

type genesClient struct {
	cc *grpc.ClientConn
}

func NewGenesClient(cc *grpc.ClientConn) GenesClient {
	return &genesClient{cc}
}

func (c *genesClient) Get(ctx context.Context, in *GetGeneRequest, opts ...grpc.CallOption) (*GetGeneResponse, error) {
	out := new(GetGeneResponse)
	err := grpc.Invoke(ctx, "/api.Genes/Get", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Genes service

type GenesServer interface {
	Get(context.Context, *GetGeneRequest) (*GetGeneResponse, error)
}

func RegisterGenesServer(s *grpc.Server, srv GenesServer) {
	s.RegisterService(&_Genes_serviceDesc, srv)
}

func _Genes_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGeneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GenesServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Genes/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GenesServer).Get(ctx, req.(*GetGeneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Genes_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Genes",
	HandlerType: (*GenesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _Genes_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/iga.proto",
}

// Client API for Evaluations service

type EvaluationsClient interface {
	Get(ctx context.Context, in *GetEvaluationRequest, opts ...grpc.CallOption) (*GetEvaluationResponse, error)
	// igaが実行される
	Set(ctx context.Context, in *SetEvaluationRequest, opts ...grpc.CallOption) (*SetEvaluationResponse, error)
}

type evaluationsClient struct {
	cc *grpc.ClientConn
}

func NewEvaluationsClient(cc *grpc.ClientConn) EvaluationsClient {
	return &evaluationsClient{cc}
}

func (c *evaluationsClient) Get(ctx context.Context, in *GetEvaluationRequest, opts ...grpc.CallOption) (*GetEvaluationResponse, error) {
	out := new(GetEvaluationResponse)
	err := grpc.Invoke(ctx, "/api.Evaluations/Get", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *evaluationsClient) Set(ctx context.Context, in *SetEvaluationRequest, opts ...grpc.CallOption) (*SetEvaluationResponse, error) {
	out := new(SetEvaluationResponse)
	err := grpc.Invoke(ctx, "/api.Evaluations/Set", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Evaluations service

type EvaluationsServer interface {
	Get(context.Context, *GetEvaluationRequest) (*GetEvaluationResponse, error)
	// igaが実行される
	Set(context.Context, *SetEvaluationRequest) (*SetEvaluationResponse, error)
}

func RegisterEvaluationsServer(s *grpc.Server, srv EvaluationsServer) {
	s.RegisterService(&_Evaluations_serviceDesc, srv)
}

func _Evaluations_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEvaluationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EvaluationsServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Evaluations/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EvaluationsServer).Get(ctx, req.(*GetEvaluationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Evaluations_Set_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetEvaluationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EvaluationsServer).Set(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Evaluations/Set",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EvaluationsServer).Set(ctx, req.(*SetEvaluationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Evaluations_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Evaluations",
	HandlerType: (*EvaluationsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _Evaluations_Get_Handler,
		},
		{
			MethodName: "Set",
			Handler:    _Evaluations_Set_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/iga.proto",
}

func init() { proto.RegisterFile("api/iga.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 342 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0x31, 0x53, 0xfa, 0x40,
	0x10, 0xc5, 0x27, 0x84, 0x30, 0x7f, 0x36, 0x7f, 0xc1, 0x39, 0x03, 0x46, 0x2c, 0xc0, 0x54, 0x54,
	0xa8, 0xb1, 0xd2, 0xa1, 0x75, 0x32, 0x5a, 0x58, 0x90, 0xc2, 0x92, 0x39, 0x26, 0x3b, 0xb8, 0x33,
	0x70, 0x89, 0xdc, 0x45, 0x3e, 0x83, 0x85, 0xdf, 0xd9, 0xc9, 0x5d, 0x08, 0xa8, 0xb1, 0xb1, 0xdc,
	0xdf, 0xbe, 0x7d, 0xd9, 0xec, 0x3b, 0x38, 0xe2, 0x19, 0x5d, 0xd2, 0x92, 0x4f, 0xb2, 0x4d, 0xaa,
	0x52, 0x66, 0xf3, 0x8c, 0x82, 0x63, 0xe8, 0x44, 0xa8, 0x22, 0x14, 0x38, 0xc3, 0xd7, 0x1c, 0xa5,
	0x0a, 0x42, 0xe8, 0x56, 0x44, 0x66, 0xa9, 0x90, 0xc8, 0x86, 0xe0, 0x2c, 0x51, 0xa0, 0xf4, 0xad,
	0x91, 0x3d, 0x76, 0xc3, 0xf6, 0x84, 0x67, 0x34, 0xd1, 0x0a, 0xc3, 0x83, 0x3e, 0x78, 0x11, 0xaa,
	0xfb, 0x37, 0xbe, 0xca, 0xb9, 0xa2, 0x54, 0xec, 0xbc, 0x1e, 0xa1, 0xf7, 0x8d, 0x97, 0x8e, 0xd7,
	0xe0, 0x62, 0x45, 0x77, 0xbe, 0x5d, 0xed, 0x7b, 0xa0, 0x3e, 0xd4, 0x04, 0x0f, 0xe0, 0xc5, 0x35,
	0xdf, 0xf8, 0x8b, 0xd5, 0x29, 0xf4, 0xe2, 0xba, 0xb5, 0x82, 0x3b, 0x80, 0x3d, 0x65, 0x7d, 0x68,
	0x15, 0xbf, 0x47, 0x89, 0x6f, 0x8d, 0xac, 0xb1, 0x33, 0x2b, 0x2b, 0xe6, 0x81, 0x53, 0x88, 0xd0,
	0x6f, 0x68, 0x6c, 0x8a, 0xe0, 0xc3, 0x82, 0x66, 0x71, 0x13, 0xd6, 0x81, 0x46, 0x35, 0xd2, 0xa0,
	0x84, 0x5d, 0xc0, 0xff, 0xed, 0x0b, 0xe2, 0x6a, 0xbe, 0xe1, 0x09, 0xe5, 0xb2, 0x9c, 0x72, 0x35,
	0x9b, 0x69, 0x54, 0x38, 0x2e, 0x70, 0x49, 0xc2, 0xb7, 0x8d, 0xa3, 0x2e, 0xd8, 0x39, 0xb4, 0xb3,
	0x94, 0x84, 0x9a, 0x8b, 0x7c, 0xed, 0x37, 0x75, 0xe7, 0x9f, 0x06, 0x4f, 0xf9, 0x9a, 0x0d, 0xc1,
	0x5d, 0x6c, 0x90, 0x4b, 0x35, 0xdf, 0x52, 0x82, 0xbe, 0xa3, 0xdb, 0x60, 0xd0, 0x33, 0x25, 0x18,
	0xde, 0x82, 0x53, 0xac, 0x23, 0xd9, 0x15, 0xd8, 0x11, 0x2a, 0x76, 0x52, 0xa6, 0x76, 0x18, 0xf6,
	0xc0, 0xfb, 0x0a, 0xcd, 0x19, 0xc2, 0x77, 0x0b, 0xdc, 0xfd, 0x1d, 0x24, 0x9b, 0x1a, 0x87, 0xb3,
	0x9d, 0xf8, 0x47, 0x08, 0x83, 0x41, 0x5d, 0xab, 0xcc, 0x7a, 0x0a, 0x76, 0x5c, 0x4d, 0xc7, 0xbf,
	0x4f, 0xd7, 0x46, 0xb2, 0x68, 0xe9, 0xc7, 0x7a, 0xf3, 0x19, 0x00, 0x00, 0xff, 0xff, 0xbd, 0x45,
	0xbe, 0x73, 0xbd, 0x02, 0x00, 0x00,
}
